"""Initial migration.

Revision ID: 251a9a3d86fd
Revises: 
Create Date: 2025-05-15 21:48:04.282036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251a9a3d86fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
